server:
  port: 8082
spring:
  application:
    name: service-oss
  profiles:
    active: dev
aliyun:
  oss:
    accessKeyId: LTAI5tGMV1jdMJQWrAUvMyMt
    accessKeySecret: Z0yA0eXj4WCufeup12jhrXokM3Mf55
    bucketName: 20201111
    endpoint: oss-cn-beijing.aliyuncs.com
    avatarPath: guLiXueYuan/avatar/
