server:
  port: 8082
spring:
  application:
    name: service-oss
  profiles:
    active: dev
aliyun:
  oss:
    accessKeyId: LTAI4Fvi9tZzMyD73JGCFTYK
    accessKeySecret: xr9u8fCaxon9RCDW22MsBcXpNHICWm
    bucketName: 20201111
    endpoint: oss-cn-beijing.aliyuncs.com
    avatarPath: guLiXueYuan/avatar/
